package model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 18 11:26:23 EST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptViewImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public DeptViewImpl()
  {
  }
}
