DROP TABLE FPA;
DROP TABLE FOURNISSEUR;
DROP TABLE PRODUIT;
DROP TABLE ATELIER;

CREATE TABLE FOURNISSEUR
    (NOF        CHAR(2) PRIMARY KEY,
    NOMF        VARCHAR2(15),
    STATUT      NUMBER(2),
    VILLE       VARCHAR2(15));

CREATE TABLE PRODUIT
    (NOP        CHAR(2) PRIMARY KEY,
    NOMP        VARCHAR2(15),   
    COULEUR     VARCHAR2(10),
    POIDS       NUMBER(2),
    VILLE       VARCHAR2(15));

CREATE TABLE ATELIER
    (NOA        CHAR(2) PRIMARY KEY,
    NOMA        VARCHAR2(15),
    VILLE       VARCHAR2(15));

-- Le produit P a été fait par F dans l'atelier A
CREATE TABLE FPA
    (NOF        CHAR(2) REFERENCES FOURNISSEUR,
    NOP         CHAR(2) REFERENCES PRODUIT,
    NOA         CHAR(2) REFERENCES ATELIER,
    QTE         NUMBER(4));


INSERT INTO FOURNISSEUR VALUES('F1','Guillemette',20,'Montreal');
INSERT INTO FOURNISSEUR VALUES('F2','Limoges',10,'Quebec');
INSERT INTO FOURNISSEUR VALUES('F3','Bergevin',30,'Quebec');
INSERT INTO FOURNISSEUR VALUES('F4','Mathieu',20,'Montreal');
INSERT INTO FOURNISSEUR VALUES('F5','Drouin',30,'Chicoutimi');

INSERT INTO PRODUIT VALUES('P1','crayon','rouge',12,'Montreal');
INSERT INTO PRODUIT VALUES('P2','cartable','vert',17,'Quebec');
INSERT INTO PRODUIT VALUES('P3','carton','bleu',17,'Rimouski');
INSERT INTO PRODUIT VALUES('P4','carton','rouge',14,'Montreal');
INSERT INTO PRODUIT VALUES('P5','brocheuse','bleu',12,'Quebec');
INSERT INTO PRODUIT VALUES('P6','étampe','rouge',19,'Montreal');

INSERT INTO ATELIER VALUES('A1','Narbec','Quebec');
INSERT INTO ATELIER VALUES('A2','Quatre Saisons','Rimouski');
INSERT INTO ATELIER VALUES('A3','Gonzales','Chicoutimi');
INSERT INTO ATELIER VALUES('A4','Offset Mt-Royal','Chicoutimi');
INSERT INTO ATELIER VALUES('A5','Plomberium','Montreal');
INSERT INTO ATELIER VALUES('A6','Grand Cirque','Gaspe');
INSERT INTO ATELIER VALUES('A7','Usinage Beta','Montreal');

INSERT INTO FPA VALUES('F1','P1','A1',200);
INSERT INTO FPA VALUES('F1','P1','A4',700);
INSERT INTO FPA VALUES('F2','P3','A1',400);
INSERT INTO FPA VALUES('F2','P3','A2',200);
INSERT INTO FPA VALUES('F2','P3','A3',200);
INSERT INTO FPA VALUES('F2','P3','A4',500);
INSERT INTO FPA VALUES('F2','P3','A5',600);
INSERT INTO FPA VALUES('F2','P3','A6',400);
INSERT INTO FPA VALUES('F2','P3','A7',800);
INSERT INTO FPA VALUES('F2','P5','A2',100);
INSERT INTO FPA VALUES('F3','P3','A1',200);
INSERT INTO FPA VALUES('F3','P4','A2',500);
INSERT INTO FPA VALUES('F4','P6','A3',300);
INSERT INTO FPA VALUES('F4','P6','A7',300);
INSERT INTO FPA VALUES('F5','P2','A2',200);
INSERT INTO FPA VALUES('F5','P2','A4',100);
INSERT INTO FPA VALUES('F5','P5','A5',500);
INSERT INTO FPA VALUES('F5','P5','A7',100);
INSERT INTO FPA VALUES('F5','P6','A2',200);
INSERT INTO FPA VALUES('F5','P1','A4',1000);
INSERT INTO FPA VALUES('F5','P3','A4',1200);
INSERT INTO FPA VALUES('F5','P4','A4',800);
INSERT INTO FPA VALUES('F5','P5','A4',400);
INSERT INTO FPA VALUES('F5','P6','A4',500);

COMMIT;